name: bactopia-summary
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - coloredlogs=15.0
  - coreutils=8.31
  - executor=23.2
  - fasteners=0.14.1
  - gettext=0.19.8.1
  - humanfriendly=9.1
  - jinja2=2.11.2
  - libcxx=11.0.1
  - libffi=3.3
  - libiconv=1.16
  - markupsafe=1.1.1
  - monotonic=1.5
  - ncurses=6.2
  - openssl=1.1.1i
  - pip=20.3.3
  - property-manager=3.0
  - python=3.9.1
  - python_abi=3.9
  - readline=8.0
  - sed=4.7
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.34.0
  - tk=8.6.10
  - tzdata=2020f
  - verboselogs=1.7
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
