name: bactopia-phyloflash
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _r-mutex=1.0.1
  - bbmap=38.87
  - bedtools=2.29.2
  - biopython=1.76
  - bowtie=1.2.3
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cairo=1.16.0
  - cctools_osx-64=949.0.1
  - certifi=2019.11.28
  - clang=11.0.0
  - clang_osx-64=11.0.0
  - clangxx=11.0.0
  - clangxx_osx-64=11.0.0
  - compiler-rt=11.0.0
  - compiler-rt_osx-64=11.0.0
  - coreutils=8.31
  - curl=7.71.1
  - emirge=0.61.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gettext=0.19.8.1
  - gfortran_impl_osx-64=7.5.0
  - gfortran_osx-64=7.5.0
  - gmp=6.2.1
  - graphite2=1.3.13
  - gsl=2.6
  - harfbuzz=2.7.2
  - htslib=1.11
  - icu=67.1
  - iqtree=2.0.3
  - isl=0.22.1
  - jpeg=9d
  - krb5=1.17.2
  - ld64_osx-64=530
  - ldid=2.1.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang-cpp11=11.0.0
  - libcurl=7.71.1
  - libcxx=11.0.1
  - libdeflate=1.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgfortran=4.0.0
  - libgfortran4=7.5.0
  - libglib=2.66.3
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.0.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - llvm-openmp=11.0.1
  - llvm-tools=11.0.0
  - lz4-c=1.9.3
  - mafft=7.475
  - make=4.3
  - mpc=1.1.0
  - mpfr=4.0.2
  - ncurses=6.2
  - numpy=1.16.5
  - openjdk=11.0.8
  - openssl=1.1.1i
  - pango=1.42.4
  - pbzip2=1.1.13
  - pcre=8.44
  - pcre2=10.35
  - perl=5.32.0
  - phyloflash=3.4
  - pigz=2.3.4
  - pip=20.1.1
  - pixman=0.40.0
  - pysam=0.16.0.1
  - python=2.7.15
  - python_abi=2.7
  - r-assertthat=0.2.1
  - r-backports=1.2.1
  - r-base=4.0.2
  - r-brio=1.1.1
  - r-callr=3.5.1
  - r-cli=2.2.0
  - r-colorspace=2.0_0
  - r-crayon=1.3.4
  - r-desc=1.2.0
  - r-diffobj=0.3.3
  - r-digest=0.6.27
  - r-ellipsis=0.3.1
  - r-evaluate=0.14
  - r-fansi=0.4.2
  - r-farver=2.0.3
  - r-getopt=1.20.3
  - r-ggdendro=0.1.22
  - r-ggplot2=3.3.3
  - r-glue=1.4.2
  - r-gtable=0.3.0
  - r-isoband=0.2.3
  - r-jsonlite=1.7.2
  - r-labeling=0.4.2
  - r-lattice=0.20_41
  - r-lifecycle=0.2.0
  - r-magrittr=2.0.1
  - r-mass=7.3_53
  - r-matrix=1.3_2
  - r-mgcv=1.8_33
  - r-munsell=0.5.0
  - r-nlme=3.1_150
  - r-optparse=1.6.6
  - r-pillar=1.4.7
  - r-pkgbuild=1.2.0
  - r-pkgconfig=2.0.3
  - r-pkgload=1.1.0
  - r-plyr=1.8.6
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.4.5
  - r-ps=1.5.0
  - r-r6=2.5.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.6
  - r-rematch2=2.1.2
  - r-reshape2=1.4.4
  - r-rlang=0.4.10
  - r-rprojroot=2.0.2
  - r-rstudioapi=0.13
  - r-scales=1.1.1
  - r-stringi=1.5.3
  - r-stringr=1.4.0
  - r-testthat=3.0.1
  - r-tibble=3.0.5
  - r-utf8=1.1.4
  - r-vctrs=0.3.6
  - r-viridislite=0.3.0
  - r-waldo=0.2.3
  - r-withr=2.4.0
  - r-zeallot=0.1.0
  - readline=8.0
  - samtools=1.11
  - scipy=1.2.1
  - sed=4.7
  - setuptools=44.0.0
  - spades=3.14.1
  - sqlite=3.34.0
  - tapi=1100.0.11
  - tbb=2020.2
  - tk=8.6.10
  - tktable=2.10
  - vsearch=2.15.1
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.8
