name: bactopia-gtdb
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - boost=1.70.0
  - boost-cpp=1.70.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - capnproto=0.6.1
  - certifi=2020.12.5
  - dendropy=4.5.2
  - fastani=1.32
  - fasttree=2.1.10
  - gsl=2.6
  - gtdbtk=1.5.0
  - hmmer=3.1b2
  - icu=67.1
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.15
  - libstdcxx-ng=9.3.0
  - lz4-c=1.9.3
  - mash=2.3
  - ncurses=6.2
  - numpy=1.20.2
  - openssl=1.1.1k
  - pip=21.1.1
  - pplacer=1.1.alpha19
  - prodigal=2.6.3
  - python=3.8.8
  - python_abi=3.8
  - readline=8.1
  - setuptools=49.6.0
  - sqlite=3.35.5
  - tk=8.6.10
  - tqdm=4.60.0
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
