name: bactopia-eggnog
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - biopython=1.76
  - boost-cpp=1.70.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - certifi=2019.11.28
  - diamond=2.0.6
  - eggnog-mapper=2.0.1
  - gettext=0.19.8.1
  - icu=67.1
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - libidn2=2.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libstdcxx-ng=9.3.0
  - libunistring=0.9.10
  - lz4-c=1.9.3
  - ncurses=6.2
  - numpy=1.16.5
  - openssl=1.1.1i
  - pip=20.1.1
  - python=2.7.15
  - python_abi=2.7
  - readline=8.0
  - setuptools=44.0.0
  - sqlite=3.34.0
  - tk=8.6.10
  - wget=1.20.1
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.8
